// Every image under public/images. Loaded on first app open so that
// subsequent navigation shows images instantly from cache.
// Keep in sync with the public/images folder.
const IMAGE_MANIFEST = [
  '/images/brand/titleIcon.png',
  '/images/brand/logo.png',
  '/images/brand/start-logo.png',
  '/images/about/3rd_colash.png',
  '/images/about/why_realcost.png',
  '/images/about/2nd_colash.png',
  '/images/about/2nd.png',
  '/images/about/hero_whyrealcost_11.png',
  '/images/about/1st_colash.png',
  '/images/about/our_bg.png',
  '/images/trades/electrical.jpg',
  '/images/trades/mechanical.jpg',
  '/images/trades/plumbing.jpg',
  '/images/trades/institutional.png',
  '/images/trades/industrial.png',
  '/images/trades/residential.png',
  '/images/trades/commercial.png',
  '/images/features/blueprint.png',
  '/images/features/takeoff.png',
  '/images/features/Canada-Map.jpg',
  '/images/features/canada-map.webp',
  '/images/features/estimating.png',
  '/images/features/gen_materials.png',
  '/images/features/features_hero.png',
  '/images/features/features_hero_mobile.png',
  '/images/features/City-Wide Pricing Network.png',
  '/images/features/Contractor-First Support.png',
  '/images/features/Digital-First Workflow.png',
  '/images/features/Expert-Built Formulas.png',
  '/images/features/Fast, Reliable Delivery.png',
  '/images/features/autocount.png',
  '/images/features/bid_page.png',
  '/images/features/estimating_graph.png',
  '/images/features/quote_letter.png',
  '/images/features/quote_send.png',
  '/images/features/take_off.png',
  '/images/home/auto_count.png',
  '/images/home/benefits_1.png',
  '/images/home/benefits_2.png',
  '/images/home/benefits_3.png',
  '/images/home/benefits_4.png',
  '/images/home/bid.png',
  '/images/home/quote.png',
  '/images/home/upload_pdf.png',
  '/images/home/home_3.png',
  '/images/home/Home.png',
  '/images/home/home_1_mobile.png',
  '/images/home/home_2_mobile.png',
  '/images/home/home_3_mobile.png',
  '/images/home/home_2.png',
  '/images/home/bid_take_off_how_it_works.png',
  '/images/home/estimating_take_off_how_it_works.png',
  '/images/home/graph_take_off_how_it_works.png',
  '/images/home/mat_list_take_off_how_it_works.png',
  '/images/home/quote_how_it_works.png',
  '/images/home/take_off_how_it_works.png',
  '/images/misc/project.jpg',
  '/images/misc/project.png',
  '/images/misc/request_demo.png',
  '/images/misc/brochure.png',
  '/images/misc/mission.png',
  '/images/misc/vision.png',
  '/images/misc/whyrealcost.png',
  '/images/misc/whyrealcost_mobile.png',
  '/images/misc/bg_our.png',
  '/images/misc/our story 11.png',
  '/images/misc/built_by_estimators.png',
  '/images/misc/meeting.png',
  '/images/contact/contact_hero.png',
  '/images/contact/uuu.png',
  '/images/faq/faq.png',
  '/images/pricing/pricing.png',
];

export default IMAGE_MANIFEST;
